### ISSUE TITLE
Pango warning when converting SVG with text to PNG

### ISSUE THREAD

**Issue by FahmiA** [gojko/librsvg-static-lambda-binary#1]
I'm getting the following error when I try to convert an SVG with text to a PNG:

`(rsvg-convert:26874): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderFc', script='latin'`

The resulting output has unreadable text.

Input SVG:
```svg
<svg xmlns="http://www.w3.org/2000/svg"
     width="500" height="40" viewBox="0 0 500 40">

  <text x="0" y="35" font-size="35">
    Hello, out there
  </text>
</svg>
```

Output PNG:
![output](https://cloud.githubusercontent.com/assets/1294158/21167675/f7781810-c212-11e6-82c5-a277bba85a1a.png)

However the SVG export works perfectly if there is no text in the SVG.

I am running on an EC2 instance and I get the same problem with the provided binary in the `vendor` folder and after I compile the binary with `compile-static.sh`.

This is not a problem when I convert the same image with the `rsvg` pulled from my package manager in Ubuntu (`rsvg-convert version 2.40.13`).

Any ideas?

**Comment by gojko** [comment]
I assume this is because pango isn't loading system fonts for some reason. The culprit is most likely in this line: https://github.com/claudiajs/rsvg-convert-aws-lambda-binary/blob/ffb90690bd93aaf3188fe44d537bf7407e28e179/compile-static.sh#L18 but I do not know enough about pango configuration to make it work. if you have time to research pango config options, that's where I'd start.

As an alternative (and to make your SVG rendering more reliable, since it's unlikely that Lambda environment has the exact fonts you expect), perhaps try linking to the font inside your SVG, using an embedded CSS font, or a CSS reference to a local file that contains the font? https://developer.mozilla.org/en/docs/Web/SVG/Tutorial/SVG_fonts

**Comment by FahmiA** [comment]
That's an interesting idea to try. I managed to get around this issue by converting the text to paths before converting to PNG. I used [text-to-svg](https://github.com/shrhdk/text-to-svg) for this.
